// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmRCkDwFlp6_nTX4YwOL2-dLVrc5-efsw',
    appId: '1:249372462749:web:a976cbaa2679df37c88e74',
    messagingSenderId: '249372462749',
    projectId: 'chat-app-d0826',
    authDomain: 'chat-app-d0826.firebaseapp.com',
    storageBucket: 'chat-app-d0826.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrEOSgvE24Peumptq4l28BoHV9tfYOHxg',
    appId: '1:249372462749:android:88b0ceadae5a8f4ec88e74',
    messagingSenderId: '249372462749',
    projectId: 'chat-app-d0826',
    storageBucket: 'chat-app-d0826.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaabqaBjf01ju-4yBHVE3LRwjlRAalUg8',
    appId: '1:249372462749:ios:b10a3343ab417d1bc88e74',
    messagingSenderId: '249372462749',
    projectId: 'chat-app-d0826',
    storageBucket: 'chat-app-d0826.appspot.com',
    iosClientId: '249372462749-4vs6cmdp2fia4i4u080nfua8a6hc4cpp.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaabqaBjf01ju-4yBHVE3LRwjlRAalUg8',
    appId: '1:249372462749:ios:b10a3343ab417d1bc88e74',
    messagingSenderId: '249372462749',
    projectId: 'chat-app-d0826',
    storageBucket: 'chat-app-d0826.appspot.com',
    iosClientId: '249372462749-4vs6cmdp2fia4i4u080nfua8a6hc4cpp.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
